# Generated by Django 5.2.13 on 2026-05-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnosis_images/')),
                ('is_skin', models.BooleanField(default=True)),
                ('skin_confidence', models.FloatField(default=0.0)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('condition_confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('severity_score', models.FloatField(default=0.0)),
                ('affected_areas', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('ai_details', models.JSONField(blank=True, default=dict)),
                ('health_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
