# Generated by Django 5.2.13 on 2026-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('external_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('treatment', 'Treatment'), ('serum', 'Serum'), ('mask', 'Face Mask')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('skin_types', models.JSONField(default=list, help_text='List of skin types this product suits')),
                ('conditions', models.JSONField(default=list, help_text='List of conditions this product helps')),
                ('rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
